function [ch]=CHAN_createNewChannel()
    ch = mlist(["chan","z","Pref","iin","Dh","Ph","Axs","q2p","G","iz","grav","rgh", ...
     "Loss","VF_opt","Cf_opt","Fi2_opt","Fi2l_opt","Dpz","vf","xa","xe"], ...
      [],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]);
endfunction
